def bilgilerigoster(ad,soyad,no,adres,tel):
    print("Adınız" ,ad)
    print("soyadınız", soyad)
    print("numaranız", no)
    print("adresiniz", adres)
    print("Telefonunuz", tel)
name=input("adınız:")
surname=input("soyadınız:")
number=int(input("numaranız:"))
adress=input("adresiniz:")
telephone=int(input("telefonunuz:"))
bilgilerigoster(ad=name ,soyad=surname, no=number,adres=adress, tel=telephone)
